name: build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Cache (PNPM)
        uses: actions/cache@v1
        with:
          path: ~/work/.pnpm-store # TODO: Query from PNPM when possible.
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: PNPM
        uses: pnpm/action-setup@v1.2.0
        with:
          run_install: true
          version: 4.14.2

      - name: Cache (build)
        uses: actions/cache@v1
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-next-

      - name: Test
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
